
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: kubeflow-user-example-com
spec:
  owner:
    kind: User
    name: user@example.com
  resourceQuotaSpec:
    hard:
      cpu: "2"
      memory: 4Gi
      persistentvolumeclaims: "1"
      requests.nvidia.com/gpu: "1"
