name: azure_ml_training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - pandas>=1.3.0
    - numpy>=1.21.0
    - scikit-learn>=1.0.0
    - joblib>=1.0.0
    - matplotlib>=3.4.0
    - seaborn>=0.11.0
    - mlflow>=1.20.0
    - azureml-mlflow>=1.40.0