name: Debug Pipeline

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check Python
      run: |
        python --version
        pip --version
        
    - name: Check directory structure
      run: |
        ls -la session-4/
        ls -la session-4/demo5-end-to-end-pipeline/
        
    - name: Check requirements
      run: |
        cat session-4/demo5-end-to-end-pipeline/requirements.txt
        
    - name: Test basic pip install
      timeout-minutes: 2
      run: |
        pip install --upgrade pip
        pip install mlflow==2.12.1
        
    - name: Test mlflow import
      run: |
        python -c "import mlflow; print('MLflow version:', mlflow.__version__)"
        
    - name: Test file operations
      run: |
        cd session-4/demo5-end-to-end-pipeline
        python -c "
        import os
        print('Current directory:', os.getcwd())
        print('Files:', os.listdir('.'))
        print('✅ Basic operations work')
        "