name: Simple MLflow Pipeline CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'session-4/demo5-end-to-end-pipeline/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'session-4/demo5-end-to-end-pipeline/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  test-pipeline:
    name: Test ML Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        cd session-4/demo5-end-to-end-pipeline
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test pipeline functionality
      run: |
        cd session-4/demo5-end-to-end-pipeline
        python test_pipeline.py
        
    - name: Run full pipeline
      if: github.ref == 'refs/heads/main'
      run: |
        cd session-4/demo5-end-to-end-pipeline
        python pipeline.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pipeline-artifacts
        path: |
          session-4/demo5-end-to-end-pipeline/pipeline_artifacts/
        retention-days: 7